### PR TITLE
fix: downgrade urfave/cli to v1 to enable more flexible parsing

### LINKED ISSUE #147: Try downgrading to `urfave/cli` v1
`urfave/cli` is currently pretty strict about the ordering of flags & args on the CLI. This breaks some of our old CLI examples that pass flags after args. There's an upstream issue to relax the ordering constraint (urfave/cli#1113), but it sounds like some users have had success in just using v1 of the module (buildkite/agent#1286). Try downgrading and see what goes wrong.

### PR DESCRIPTION
**Pull request by danxmoran**
Closes #147

I've confirmed that rebasing #150 onto this branch fixes the breaking change (I can pass the stack ID before or after the `-f` flag).

### CODE REVIEW

File: clients/helpers.go [hunk 1]
```diff
@@ -5,20 +5,17 @@ import (
...
 	"strings"
-
-	"github.com/urfave/cli/v2"
 )
 
 // ReadQuery reads a Flux query into memory from a --file argument, args, or stdin
-func ReadQuery(ctx *cli.Context) (string, error) {
-	nargs := ctx.NArg()
-	file := ctx.String("file")
+func ReadQuery(filepath string, args []string) (string, error) {
```
Comment (danxmoran) [inline clients/helpers.go:11]: The changes here are to allow kapacitor to upgrade `influx-cli` without needing to downgrade `urfave/cli` from v2 to v1. This was the only function that broke when I tried an upgrade locally.

Comment (wbaker85) [reply clients/helpers.go:11]: Hmm can you help me out a bit on what this means? Since this PR is downgrading from v2 to v1 I'm not sure I follow. Is it because kapacitor uses `urfave/cli` v2?

File: cmd/influx/backup.go [hunk 2]
```diff
@@ -6,15 +6,15 @@ import (
 	"github.com/influxdata/influx-cli/v2/clients/backup"
 	br "github.com/influxdata/influx-cli/v2/internal/backup_restore"
 	"github.com/influxdata/influx-cli/v2/pkg/cli/middleware"
-	"github.com/urfave/cli/v2"
+	"github.com/urfave/cli"
 )
 
-func newBackupCmd() *cli.Command {
```
Comment (wbaker85) [inline cmd/influx/backup.go:12]: Mostly out of curiosity...why did these all have to change from being pointers?

Comment (wbaker85) [reply cmd/influx/backup.go:12]: Guess it would help if I read the migration guide: https://github.com/urfave/cli/blob/master/docs/migrate-v1-to-v2.md#commands-are-now-lists-of-pointers

Although I do still wonder why that was 😃

File: clients/helpers.go (hunk 1 above)
Comment (danxmoran) [reply clients/helpers.go:11]: Kapacitor imports `influx-cli` as a dependency so it can reuse the business logic under `clients/` (including this function). It also implements its own CLI front-end for the tasks, using `urfave/cli/v2`. Downgrading the module in `influx-cli` changed the type of the `cli.Context` here, breaking the calls in Kapacitor. This change is still breaking, but it's easier to work around than the alternatives of either downgrading urfave or somehow using both versions there.

I'd been trying to keep any references to `urfave/cli` out of the `clients/` package to give us more flexibility in situations like this. This one slipped through the cracks, so I'm glad to refactor it away.

File: cmd/influx/backup.go (hunk 2 above)
Comment (danxmoran) [reply cmd/influx/backup.go:12]: The types changed for some reason between V1->V2 of urfave. The migration guide is [here](https://github.com/urfave/cli/blob/master/docs/migrate-v1-to-v2.md), I effectively applied it in reverse.

**Comment by wbaker85** [comment]
Everything looks good in the code as far as I can tell, but I have a higher level question as well - Is the issue with v2 breaking the old CLI examples really just related to examples - docs examples I'm guessing? I'm thinking along the lines of updating the examples vs. using an older version of `urfave`.

Updating a bunch of docs wouldn't be very much fun but that might have some pros instead of working with an older/not maintained package. If there's more significant breakages that would occur with the new behavior maybe it would outweigh that though.

**Comment by danxmoran** [comment]
> Is the issue with v2 breaking the old CLI examples really just related to examples - docs examples I'm guessing?

Yes, across our public docs, help text, and (I'd guess) blog posts. I think it's something we could eventually phase out w/ proper deprecation notice, but I think it'd be a big lift to update everything in time for the new CLI release (esp. given the time pressure). I think minimizing the number of big incompatibilities will be important to get people to go through the effort of migrating to the new version; we're still paying for some big mismatches between v1 and v2, I don't want to add another layer of problems between v2.0 and v2.1.

I checked the release dates of `urfave/cli`. `v2.3.0` and `v1.22.5` were released within a day of each other, so I don't think we're regressing to a version that hasn't seen any maintenance.

**Comment by wbaker85** [comment]
> > Is the issue with v2 breaking the old CLI examples really just related to examples - docs examples I'm guessing?
> 
> Yes, across our public docs, help text, and (I'd guess) blog posts. I think it's something we could eventually phase out w/ proper deprecation notice, but I think it'd be a big lift to update everything in time for the new CLI release (esp. given the time pressure). I think minimizing the number of big incompatibilities will be important to get people to go through the effort of migrating to the new version; we're still paying for some big mismatches between v1 and v2, I don't want to add another layer of problems between v2.0 and v2.1.
> 
> I checked the release dates of `urfave/cli`. `v2.3.0` and `v1.22.5` were released within a day of each other, so I don't think we're regressing to a version that hasn't seen any maintenance.

**Review by wbaker85 — APPROVED** [review]
