### PR TITLE
fix: avoid panic on empty tag value

### LINKED ISSUE #542: influx v1 shell crash
An external reporter sent an issue in for an InfluxQL crash in influx-cli. Tested with influxdb2 2.7.6-1 and influxdb2-cli 2.7.5-1 on Ubuntu 20.04 LTS amd64.

```
$  export V1AUTH=$(echo -n "anything:$TOKEN" | base64 --wrap 0)

# generate some line protocol 
$ cat > file.lp <<EOM
t0,t0_tag0=initTag t0_f0=0i 1715694000
t0,t0_tag0=initTag t0_f0=1i 1715694001
t0,t0_tag1=initTag t0_f0=0i 1715694000
EOM

# write
$ curl -H "Authorization: Basic $V1AUTH" -X POST "$URL/write?db=test1&precision=s" --data-binary @./file.lp
$
```

Simple query works:
```
$ influx v1 shell --host $URL --token $TOKEN
InfluxQL Shell dev
Connected to InfluxDB OSS v2.7.6
> USE test1
> select * from t0
Interactive Table View (press q to exit mode, shift+up/down to navigate tables):
Name: t0
┏━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┓
┃ index ┃              time              ┃    t0_f0     ┃ t0_tag0 ┃ t0_tag1 ┃
┣━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━╋━━━━━━━━━╋━━━━━━━━━┫
┃      1┃  1715694000000000000.0000000000┃  0.0000000000┃initTag  ┃    <nil>┃
┃      2┃  1715694000000000000.0000000000┃  0.0000000000┃<nil>    ┃  initTag┃
┃      3┃  1715694001000000000.0000000000┃  1.0000000000┃initTag  ┃    <nil>┃
┣━━━━━━━┻━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┻━━━━━━━━━━━━━━┻━━━━━━━━━┻━━━━━━━━━┫
┃                                                5 Columns, 3 Rows, Page 1/1┃
┃                                                   Table 1/1, Statement 1/1┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
```

This one crashes:
```
$ influx v1 shell --host $URL --token $TOKEN
InfluxQL Shell dev
Connected to InfluxDB OSS v2.7.6
> USE test1
> SELECT * FROM test1.autogen.t0 WHERE ((2514049662u) ^ (((0) != (201203873)) OR (''))) GROUP BY t1_tag0, t1_f0 ORDER BY  DESC LIMIT 2147483647
panic: runtime error: slice bounds out of range [:-2] [recovered]
	panic: close of nil channel

goroutine 1 [running]:
github.com/charmbracelet/bubbletea.(*standardRenderer).kill.func1()
	/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/standard_renderer.go:91 +0x1b
sync.(*Once).doSlow(0xe2a380?, 0xc000078028?)
	/go/src/sync/once.go:74 +0xbf
sync.(*Once).Do(...)
	/go/src/sync/once.go:65
github.com/charmbracelet/bubbletea.(*standardRenderer).kill(0xc0002180a0)
	/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/standard_renderer.go:90 +0x92
github.com/charmbracelet/bubbletea.(*Program).shutdown(0xc0003a8000, 0x0?)
	/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/tea.go:584 +0x42
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel.func3()
	/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/tea.go:369 +0x45
panic({0xc6dbe0?, 0xc000384060?})
	/go/src/runtime/panic.go:920 +0x270
github.com/influxdata/influx-cli/v2/clients/v1_shell.Model.Init({{0xc0003a406c, 0x2}, 0xc0003800c0, 0x1, 0x1, 0x1, 0x1, {0xc0003a0000, 0x3, 0x3}, ...})
	/root/project/clients/v1_shell/table_model.go:180 +0x4b0
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel(0xc0003a8000)
	/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/tea.go:400 +0x6cd
github.com/influxdata/influx-cli/v2/clients/v1_shell.(*Client).outputTable(0xc000278b60, {0xc000386030})
	/root/project/clients/v1_shell/v1_shell.go:662 +0x4cb
github.com/influxdata/influx-cli/v2/clients/v1_shell.(*Client).runAndShowQuery(0xc000278b60, {0xc0004bf680?, 0xe27dc8?})
	/root/project/clients/v1_shell/v1_shell.go:369 +0x525
github.com/influxdata/influx-cli/v2/clients/v1_shell.(*Client).executor(0xc000278b60, {0xc0004bf680, 0x8d})
	/root/project/clients/v1_shell/v1_shell.go:214 +0x5e5
github.com/influxdata/go-prompt.(*Prompt).Run(0xc00030e120)
	/go/pkg/mod/github.com/influxdata/go-prompt@v0.2.8/prompt.go:84 +0x73f
github.com/influxdata/influx-cli/v2/clients/v1_shell.(*Client).Create(0xc000278b60, {0xe2f620, 0xc000260820})
	/root/project/clients/v1_shell/v1_shell.go:168 +0x4eb
main.newV1ShellCmd.func1(0xc0001aa840)
	/root/project/cmd/influx/v1_shell.go:41 +0x35a
github.com/urfave/cli.HandleAction({0xbbbe20?, 0xc000010798?}, 0x5?)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0x50
github.com/urfave/cli.Command.Run({{0xccd4d2, 0x5}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xce71db, 0x17}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x63e
github.com/urfave/cli.(*App).RunAsSubcommand(0xc000264380, 0xc0001aa580)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405 +0xdc7
github.com/urfave/cli.Command.startApp({{0xccbff7, 0x2}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xcf0771, 0x1f}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372 +0xb58
github.com/urfave/cli.Command.Run({{0xccbff7, 0x2}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xcf0771, 0x1f}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102 +0x7e5
github.com/urfave/cli.(*App).Run(0xc0001fe540, {0xc00023df10, 0x6, 0x7})
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0xb07
main.main()
	/root/project/cmd/influx/main.go:124 +0xc6
```

So does this one when pressing 'shift+down arrow' to page down:
```
$ influx v1 shell --host $URL --token $TOKEN
InfluxQL Shell dev
Connected to InfluxDB OSS v2.7.6
> USE test1
> SELECT * FROM test1.autogen.t0 WHERE ((2514049662u) ^ (((0) != (201203873)) OR (''))) GROUP BY t0_tag0 ORDER BY  DESC LIMIT 2147483647
panic: runtime error: slice bounds out of range [:-2] [recovered]
	panic: close of nil channel

goroutine 1 [running]:
github.com/charmbracelet/bubbletea.(*standardRenderer).kill.func1()
	/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/standard_renderer.go:91 +0x1b
sync.(*Once).doSlow(0xe2a380?, 0xc000078028?)
	/go/src/sync/once.go:74 +0xbf
sync.(*Once).Do(...)
	/go/src/sync/once.go:65
github.com/charmbracelet/bubbletea.(*standardRenderer).kill(0xc0001441e0)
	/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/standard_renderer.go:90 +0x92
github.com/charmbracelet/bubbletea.(*Program).shutdown(0xc0000dc420, 0x0?)
	/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/tea.go:584 +0x42
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel.func3()
	/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/tea.go:369 +0x45
panic({0xc6dbe0?, 0xc000028390?})
	/go/src/runtime/panic.go:920 +0x270
github.com/influxdata/influx-cli/v2/clients/v1_shell.Model.Init({{0xc000122118, 0x2}, 0xc0001bb440, 0x1, 0x1, 0x2, 0x2, {0xc0002a4450, 0x1, 0x1}, ...})
	/root/project/clients/v1_shell/table_model.go:180 +0x4b0
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel(0xc0000dc420)
	/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/tea.go:400 +0x6cd
github.com/influxdata/influx-cli/v2/clients/v1_shell.(*Client).outputTable(0xc000103040, {0xc00012c048})
	/root/project/clients/v1_shell/v1_shell.go:662 +0x4cb
github.com/influxdata/influx-cli/v2/clients/v1_shell.(*Client).runAndShowQuery(0xc000103040, {0xc00027a000?, 0xe27dc8?})
	/root/project/clients/v1_shell/v1_shell.go:369 +0x525
github.com/influxdata/influx-cli/v2/clients/v1_shell.(*Client).executor(0xc000103040, {0xc00027a000, 0x86})
	/root/project/clients/v1_shell/v1_shell.go:214 +0x5e5
github.com/influxdata/go-prompt.(*Prompt).Run(0xc00029e120)
	/go/pkg/mod/github.com/influxdata/go-prompt@v0.2.8/prompt.go:84 +0x73f
github.com/influxdata/influx-cli/v2/clients/v1_shell.(*Client).Create(0xc000103040, {0xe2f620, 0xc000114000})
	/root/project/clients/v1_shell/v1_shell.go:168 +0x4eb
main.newV1ShellCmd.func1(0xc000136160)
	/root/project/cmd/influx/v1_shell.go:41 +0x35a
github.com/urfave/cli.HandleAction({0xbbbe20?, 0xc000010798?}, 0x5?)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0x50
github.com/urfave/cli.Command.Run({{0xccd4d2, 0x5}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xce71db, 0x17}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x63e
github.com/urfave/cli.(*App).RunAsSubcommand(0xc000124000, 0xc0001aa580)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405 +0xdc7
github.com/urfave/cli.Command.startApp({{0xccbff7, 0x2}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xcf0771, 0x1f}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372 +0xb58
github.com/urfave/cli.Command.Run({{0xccbff7, 0x2}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xcf0771, 0x1f}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102 +0x7e5
github.com/urfave/cli.(*App).Run(0xc0001fe540, {0xc00023ff10, 0x6, 0x7})
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0xb07
main.main()
	/root/project/cmd/influx/main.go:124 +0xc6
```

This is not considered security relevant as it is a crash in an interactive CLI tool where the tool is aborting and not under attacker control.

### LINKED ISSUE #547: A crash bug is triggered when using GroupBy while querying FIELD KEY CARDINALITY.
#### Steps to reproduce

In the latest version of InfluxDB, if we have an organization named "organization", we can use the Influx client to execute the following commands to create a bucket and write the specified data into that bucket.

```
influx bucket delete --name db0
influx bucket create --name db0 --org organization

influx write \
  --bucket db0 \
  --precision s "
t0,t0_tag0=initTag t0_f0=0u 1641024000
t0,t0_tag0=initTag t0_f0=1u 1641024001
t0,t0_tag1=initTag t0_f0=0u 1641024000"
```

Next, we use the `Influx v1 shell` command to enter the Influx shell backend and execute three types of query statements:

```
# query 1
SHOW FIELD KEY CARDINALITY FROM db0.autogen.t0

# query 2
SHOW FIELD KEY CARDINALITY FROM db0.autogen.t0 WHERE ('a' !=  (t0_tag0))

# query 3
SHOW FIELD KEY CARDINALITY FROM db0.autogen.t0 WHERE ('a' !=  (t0_tag0)) GROUP BY t0_tag0
```

#### Expected behaviour

The above query statements should execute successfully and return the corresponding results.

#### Actual behaviour

When executing query1 and query2, the Influx shell is able to return the correct results. However, when executing query3, the Influx shell **exits unexpectedly** and reports the following error:

```
panic: runtime error: slice bounds out of range [:-2] [recovered]
        panic: close of nil channel

goroutine 1 [running]:
github.com/charmbracelet/bubbletea.(*standardRenderer).kill.func1()
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/standard_renderer.go:91 +0x1b
sync.(*Once).doSlow(0xe2a380?, 0xc000110020?)
        /go/src/sync/once.go:74 +0xbf
sync.(*Once).Do(...)
        /go/src/sync/once.go:65
github.com/charmbracelet/bubbletea.(*standardRenderer).kill(0xc00021c960)
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/standard_renderer.go:90 +0x92
github.com/charmbracelet/bubbletea.(*Program).shutdown(0xc00014e790, 0x0?)
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/tea.go:584 +0x42
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel.func3()
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/tea.go:369 +0x45
panic({0xc6dbe0?, 0xc000148318?})
        /go/src/runtime/panic.go:920 +0x270
github.com/influxdata/influx-cli/v2/clients/v1_shell.Model.Init({{0xc0002a4a6c, 0x2}, 0xc00028fbc0, 0x1, 0x1, 0x1, 0x1, {0xc00028fbf0, 0x1, 0x1}, ...})
        /root/project/clients/v1_shell/table_model.go:180 +0x4b0
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel(0xc00014e790)
```
We suspect that this is a crash bug.

#### Environment info

Influx CLI dev (git: none) build_date: 2023-04-28T14:24:14Z

InfluxDB OSS v2.7.10 (git: f302d97)

Linux 5.15.0-94-generic x86_64

### PR DESCRIPTION
**Pull request by karel-rehor**
Fixes #547
Fixes #542

### Current state

Currently, when the method `func (m Model) Init()` is called on a result containing a tag with an empty value (e.g. `"tags":{"state":""}`), the program panics on the line (`fmt.Print(tagline[:len(tagline)-2])`).

### Proposed change

in `table_modle.go` when the method `func (m Model) Init()` is called with a result containing a tag with an empty value (e.g. `"tags":{"state":""}`), the empty value is substituted in the tea model with a default presentation string ` ----- ` suggesting an empty value was found.

### CODE REVIEW

File: clients/v1_shell/table_model.go [hunk 1]
```diff
@@ -171,9 +171,12 @@ func (m Model) Init() tea.Cmd {
 	if len(m.tags) > 0 {
 		fmt.Print("Tags: ")
 		for key, val := range m.tags {
-			if key == "" || val == "" {
+			if key == "" {
 				continue
 			}
+			if val == "" {
+				val = " ----- "
```
Comment (bednar) [inline clients/v1_shell/table_model.go:178]: What do you think about using something like <empty>, similar to <nil>?

Comment (karel-rehor) [reply clients/v1_shell/table_model.go:178]: I'm not sure I understand the question.  Are you suggesting using a blank line or a comma?  The field at this point is mostly presentational.  I think it's important to have a pseudo-graphic signifier that suggests the key was tried and that unambiguously it returned an empty value.  A blank line as a signifier leaves a far more open set of possible interpretations. 

For the query `SHOW FIELD KEY CARDINALITY FROM test.autogen.iota GROUP BY id`

Currently
```
Interactive Table View (press q to exit mode, shift+up/down to navigate tables):
Name: iota
Tags: id= ----- 
┏━━━━━━━┳━━━━━━━━━━━━━━┓
┃ index ┃    count     ┃
┣━━━━━━━╋━━━━━━━━━━━━━━┫
┃      1┃  1.0000000000┃
┣━━━━━━━┻━━━━━━━━━━━━━━┫
┃    2 Columns, 1 Rows,┃
┃              Page 1/1┃
┃  Table 1/1, Statement┃
┃                   1/1┃
┗━━━━━━━━━━━━━━━━━━━━━━┛
```
Proposed?
```
Interactive Table View (press q to exit mode, shift+up/down to navigate tables):
Name: iota
Tags: id=
┏━━━━━━━┳━━━━━━━━━━━━━━┓
┃ index ┃    count     ┃
┣━━━━━━━╋━━━━━━━━━━━━━━┫
┃      1┃  1.0000000000┃
┣━━━━━━━┻━━━━━━━━━━━━━━┫
┃    2 Columns, 1 Rows,┃
┃              Page 1/1┃
┃  Table 1/1, Statement┃
┃                   1/1┃
┗━━━━━━━━━━━━━━━━━━━━━━┛
```

Comment (karel-rehor) [reply clients/v1_shell/table_model.go]: OK following Vlasta's recommendation empty tag values now render like this

```
Interactive Table View (press q to exit mode, shift+up/down to navigate tables):
Name: iota
Tags: id= <nil> 
┏━━━━━━━┳━━━━━━━━━━━━━━┓
┃ index ┃    count     ┃
┣━━━━━━━╋━━━━━━━━━━━━━━┫
┃      1┃  1.0000000000┃
┣━━━━━━━┻━━━━━━━━━━━━━━┫
┃    2 Columns, 1 Rows,┃
┃              Page 1/1┃
┃  Table 1/1, Statement┃
┃                   1/1┃
┗━━━━━━━━━━━━━━━━━━━━━━┛
```

File: clients/v1_shell/table_model.go [hunk 2]
```diff
@@ -171,9 +171,12 @@ func (m Model) Init() tea.Cmd {
 	if len(m.tags) > 0 {
 		fmt.Print("Tags: ")
 		for key, val := range m.tags {
-			if key == "" || val == "" {
+			if key == "" {
 				continue
 			}
+			if val == "" {
+				val = " <nil> "
```
Comment (vlastahajek) [inline clients/v1_shell/table_model.go:178]: Why empty spaces around?

Comment (karel-rehor) [reply clients/v1_shell/table_model.go:178]: So that when it is rendered in bubbletea that it will stand out from the equal sign.

Comment (vlastahajek) [reply clients/v1_shell/table_model.go:178]: But, why such a difference? AFAIK, the real values are not rendered with a space in front of it, nor `<nil>` in the table view.

Comment (karel-rehor) [reply clients/v1_shell/table_model.go]: It's a question of presentation, which IMHO looks cleaner with a space between the equals sign and the bracket. At this point `val` is only needed for presentation and will not be used further.  However, this is a triviality, so the change has been made.

Comment (vlastahajek) [reply clients/v1_shell/table_model.go]: I understand the idea, but we must make compatible and consistent changes.  So, if spaces, the space should be presented on both sides of the equal sign and it should also be added if real value (not placeholder) is presented.

**Review by vlastahajek — APPROVED** [review]
👍

**Review by bednar — APPROVED** [review]

**Review by bednar — APPROVED** [review]
LGTM 👍
