### PR TITLE
fix: v1 auth create command supports multiple buckets

### LINKED ISSUE #327: `v1 auth create` command supports no multiple read or write buckets
I use influx-cli version `2.2.0`

```bash
$ influx version
Influx CLI 2.2.0 (git: c3690d8) build_date: 2021-10-21T15:24:59Z
```

I'm getting the bug with `v1 auth create` command. It was created with same bucket id in permissions.

```bash
$ influx v1 auth create \
  --username example-user \
  --password example-password \
  --org example-org \
  --read-bucket 0d4d9f7c8ab4eff8 \
  --read-bucket 7cc7853adce272e4 \
  --json
{
        "id": "086f2cfbaa17f000",
        "description": "",
        "token": "example-user",
        "status": "active",
        "userName": "root",
        "userID": "086cec9862d40000",
        "permissions": [
                "read:orgs/b48cd0e56084049b/buckets/7cc7853adce272e4",
                "read:orgs/b48cd0e56084049b/buckets/7cc7853adce272e4"
        ]
}
```

It seems this bug is not resolved latest version(2.2.1).

### PR DESCRIPTION
**Pull request by ymmmtym**
Closes #327

### CODE REVIEW

**Comment by ymmmtym** [comment]
## debug

```bash
var permissions []api.Permission
        for _, bp := range bucketPerms {
-               for _, p := range bp.perms {
+               for _, _p := range bp.perms {
+                       p := _p
                        // verify the input ID
                        if err := influxid.Validate(p); err != nil {
                                return fmt.Errorf("invalid bucket ID '%s': %w (did you pass a bucket name instead of an ID?)", p, err)
@@ -113,7 +114,10 @@ func (c Client) Create(ctx context.Context, params *CreateParams) error {
                                        OrgID: &orgID,
                                },
                        }
+                       // debug
+                       fmt.Printf("permission=%v\n",newPerm)
                        permissions = append(permissions, newPerm)
+                       fmt.Printf("len=%d cap=%d permissions=%v\n", len(permissions), cap(permissions), permissions)
                }
        }
```

output

```bash
$ influx v1 auth create \
  --username example-user \
  --password example-password \
  --org example-org \
  --read-bucket 0d4d9f7c8ab4eff8 \
  --read-bucket 7cc7853adce272e4 \
  --json

permission=read:orgs/b48cd0e56084049b/buckets/0d4d9f7c8ab4eff8
len=1 cap=1 permissions=[read:orgs/b48cd0e56084049b/buckets/0d4d9f7c8ab4eff8]
permission=read:orgs/b48cd0e56084049b/buckets/7cc7853adce272e4
len=2 cap=2 permissions=[read:orgs/b48cd0e56084049b/buckets/0d4d9f7c8ab4eff8 read:orgs/b48cd0e56084049b/buckets/7cc7853adce272e4]
{
        "id": "086f34d8c117f000",
        "description": "",
        "token": "example-user",
        "status": "active",
        "userName": "root",
        "userID": "086cec9862d40000",
        "permissions": [
                "read:orgs/b48cd0e56084049b/buckets/0d4d9f7c8ab4eff8",
                "read:orgs/b48cd0e56084049b/buckets/7cc7853adce272e4"
        ]
}
```

File: clients/v1_auth/v1_auth.go [hunk 1]
```diff
@@ -99,7 +99,8 @@ func (c Client) Create(ctx context.Context, params *CreateParams) error {
 
 	var permissions []api.Permission
 	for _, bp := range bucketPerms {
-		for _, p := range bp.perms {
+		for _, _p := range bp.perms {
+			p := _p
```
Comment (danxmoran) [inline clients/v1_auth/v1_auth.go:103]: This would be more idiomatic IMO, and would prevent accidental references to the wrong `p` value:
```suggestion
		for _, p := range bp.perms {
			p := p
```

**Review by danxmoran — COMMENTED** [review]
Thanks for the contribution! Could you please sign the [CLA](https://influxdata.com/community/cla/)?

File: clients/v1_auth/v1_auth.go (hunk 1 above)
Comment (ymmmtym) [reply clients/v1_auth/v1_auth.go]: thanks for your review!!
I updated the commit for your suggestion.

**Comment by ymmmtym** [comment]
Thanks for your review.
I sent InfluxData CLA from Google form.

**Review by danxmoran — APPROVED** [review]
Thanks again!
